### ISSUE TITLE
1.9.4-1.3 server config doesn't sync to client

### ISSUE THREAD

**Issue by kreezxil** [delvr/Streams#18]
Or rather it appears to not do so.

In my server config I have

repose.slopingBlocks=Both

my client has the default

When I walk around in my server world, I can easily climb all of the granular blocks, but when it comes to stone based blocks, I have to hit jump, by your description "Both" should mean that I shouldn't have to be doing that.

... therefore ... I think that mod doesn't sync to the client the servers config.

**Comment by delvr** [comment]
This should be in the Repose repo but anyway, that config is a bit weird because part of it affects the client and part of it affects the server. I've been recommending keeping them in sync but automating that would be nice. Might need custom network packets which I haven't used before though, so it might take a bit of time.

**Comment by delvr** [comment]
This issue was moved to delvr/Repose#14
