### ISSUE TITLE
1.12.2 Streams & Journeymap

### ISSUE THREAD

**Issue by Zygus42** [delvr/Streams#57]
A lot of versions ago, Streams used to show as gray instead of blue on Journeymap' maps.  Then this was fixed and they were blue.  As of a couple of versions ago, the streams that were showing as blue are now gray again with the occasional blue pixel.  What I'm not sure about is whether it was versions of Streams mod or Journeymap mod that changed this back.  I'm reporting this here, but please let me know if I should report this on Journeymap's issues instead.

**Comment by delvr** [comment]
This would probably be on JourneyMap's side, as they're the ones assigning colors to blocks. If they can do it using the water material instead of specific water blocks, it should work.

That said, looking online I hear there's supposed to be `colorpalette.json` in the `journeymap` dir that allows assigning custom colors to blocks, but I don't see that file in the version I just tested (5.5.2).

**Comment by mysticdrew** [comment]
I've added support to Journeymap 5.5.4 beta 5.

**Comment by delvr** [comment]
Thanks for your help mysticdrew!
