### ISSUE TITLE
Streams don't generate with higher sea level?

### ISSUE THREAD

**Issue by Arakhor** [delvr/Streams#58]
I've changed sea level in my world to 101 and bumped terrain heights up as well, the terrain looks like streams should generate just fine, but I had no luck finding any in thousands of chunks.
Picture of the terrain:
https://i.imgur.com/hmsjWUr.jpg

**Comment by delvr** [comment]
Hi Arakhor, thanks for reporting this. It should be fixed in the new Streams 0.4.4, please let me know if you still don't find streams. (You can use the game log to locate them as described in the [FAQ in the forum post](https://www.minecraftforum.net/forums/mapping-and-modding-java-edition/minecraft-mods/2346379-streams-real-flowing-rivers)).
