### ISSUE TITLE
[Repose Compat] Standing on stairs near water applies drag to player

### ISSUE THREAD

**Issue by CREEATION** [delvr/Streams#71]
Standing on the lower part of a stair (or in my case, the Repose mod) makes a water stream catch you, even if you aren't standing in the water.

Demonstration:
![mc_stream_bug](https://user-images.githubusercontent.com/3277769/54916901-d727a180-4efa-11e9-91d0-fd4497305495.gif)

I assume this can't be fixed since the original stream block is just a regular-height block?

Maybe making Repose not apply stair collisions when the block is touching water could be a quick fix for this.

**Comment by CREEATION** [comment]
Additionally, as seen in the GIF, this also means you can't sneak to the edge of a water stream without falling in.

**Comment by delvr** [comment]
Hi Creeation, thanks for the suggestion! As mentioned in the linked Repose issue, I don't think I'll remove Repose slopes near water, in order to preserve the ability to walk out of water using them. As for stairs and non-Repose half-blocks, it seems to me that drag is applied when the player's feet do touch the water (you can see the bubbles forming in your .gif for example). This matches default Vanilla behavior so I'd prefer to hear more about scenarios of major inconvenience before altering that.

**Comment by CREEATION** [comment]
This might better fit into the Repose repository? I edited the Repose parts in later, so this issue doesn't really apply to Streams I think.

//e:
> it seems to me that drag is applied when the player's feet do touch the water (you can see the bubbles forming in your .gif for example)

As seen in the GIF, the feet don't touch the water (visually) when the stream catches the player. While this matches vanilla behaviour with stairs which are visibly stairs and not blocks, it's counter-intuitive for (visually) full blocks.

//e²: My initial issue wasn't about stairs in general, but the Repose-transformed blocks. So I'll close this one. 🐢 

//e³: I haven't tested normal flowing water (which isn't a block high) with stairs, so my issue might still be valid. Not sure. Feel free to re-open if you think it is.
